<?php include 'include/header.php'; ?>
	<h1>End-user license agreement</h1>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium ducimus neque provident, eius voluptates doloribus tenetur. Magnam libero, minima modi labore molestiae quidem unde, illum doloremque voluptatum beatae, sint consequatur!</p>
	<p>Voluptatum magnam, quisquam accusamus quas dignissimos, laboriosam esse dolor aut assumenda, doloribus odit nobis nam doloremque facere dolore neque quaerat at distinctio possimus odio! Quibusdam placeat vitae aliquid, architecto quo.</p>
	<p>Odit saepe, labore repudiandae dolor sequi accusantium, animi dignissimos, laboriosam assumenda impedit, facilis mollitia eos nisi eligendi fuga sint hic unde molestias illo. Sit blanditiis at quam numquam officiis ipsum.</p>
	<p>Ab eveniet dolorem in esse qui ducimus, ut inventore beatae molestias odio, ullam itaque nemo praesentium eaque quos! Dolor magnam reprehenderit esse aliquid quo iste voluptatibus? Error consequatur consequuntur in!</p>
	<p>A corporis ut animi vel et optio natus nihil. Eligendi, quidem. Tempora adipisci pariatur quidem et dolorem a tenetur aspernatur repellat dicta quae? Iure perferendis deleniti quas asperiores, hic veniam!</p>
	<p>Dolorum saepe nam accusantium facere cupiditate maiores facilis atque ratione, iure, ipsa odit eius, necessitatibus voluptatem omnis? Architecto voluptatem veniam necessitatibus totam, explicabo dolores non, veritatis aliquid, magni reiciendis possimus!</p>
	<p>Voluptate modi, hic dignissimos, eum, inventore asperiores nihil nostrum quidem earum sint optio aliquam quis, nulla ex. Illum obcaecati reiciendis tenetur, ipsam inventore. Aut, eligendi iusto velit necessitatibus earum perferendis.</p>
	<p>Fugit error, rem! Obcaecati atque id deserunt nobis enim placeat, magnam inventore porro totam sequi maxime et repudiandae excepturi sapiente ratione veniam. Eveniet eligendi sequi atque dicta quidem sapiente maiores!</p>
	<p>Veniam soluta quod magni voluptatibus nulla sunt dolore nemo eos, praesentium voluptates maxime neque libero ipsa veritatis, fugiat esse perspiciatis nam! Voluptatem, impedit consequatur illum rem optio commodi nemo enim.</p>
	<p>Rem temporibus ut nisi cupiditate facere quisquam quos reiciendis totam nulla deserunt accusamus corporis quae animi reprehenderit perspiciatis debitis enim dicta eos voluptates in dolorem nobis est aspernatur, consequuntur! At!</p>
	<p>Praesentium nihil enim sint consequuntur? Delectus possimus nulla, ut suscipit magnam ea, nesciunt nam recusandae vero velit culpa itaque voluptatibus rerum, eos? Dolorem eaque eius perferendis? Aperiam autem nulla, architecto.</p>
	<p>Repellendus pariatur labore assumenda sapiente, repellat iusto necessitatibus, totam error inventore, quas earum dolore debitis recusandae, fugit. Aliquam deserunt beatae nostrum architecto modi nam quae expedita possimus doloremque quisquam, dolore.</p>
	<p>Voluptatum eos illo deserunt natus, sed, rerum voluptatibus, aperiam consectetur a ipsam quam. At nam sapiente laborum tempore sit temporibus ad laboriosam porro nostrum, quae, ipsam voluptatibus, eaque ullam quam.</p>
	<p>Similique rem iure dolores deleniti sed, reprehenderit corrupti fugiat, nisi illo sequi maxime ad assumenda numquam. Possimus vero impedit dolore, perferendis excepturi, enim quis voluptates provident, temporibus in facilis non.</p>
	<p>Odio magnam corporis officia doloribus autem facilis voluptatem molestiae fuga maxime assumenda, tempore excepturi voluptatibus aut perspiciatis fugit labore deserunt accusantium sint rerum ratione provident! Sequi ad voluptatem laborum quasi.</p>
	<p>Ipsa fuga quia, temporibus enim voluptas laudantium ratione deserunt neque suscipit minus natus, quidem incidunt fugiat et itaque accusantium veniam quam molestiae tenetur aut maiores saepe! Pariatur eum ad delectus.</p>
	<p>Officia tempore voluptatum praesentium placeat, blanditiis libero asperiores repellat est harum eos corporis cum excepturi repellendus sequi iure consequuntur reprehenderit quibusdam exercitationem, voluptate dignissimos ab dolorem dolor aliquid mollitia. Eius!</p>
	<p>Quos tenetur sint, itaque error modi est! Delectus repudiandae error, voluptate tempora nobis dolorum sunt odio. Omnis pariatur nostrum eveniet facere, saepe explicabo perspiciatis? Animi veniam aut doloribus, illo assumenda!</p>
	<p>Doloribus cupiditate vero molestias itaque voluptatum deserunt rem distinctio facere consequatur nulla repudiandae, harum omnis similique, debitis suscipit officiis repellendus animi et, inventore accusantium iste nemo. Saepe a blanditiis nostrum.</p>
	<p>Praesentium consectetur unde ducimus nihil modi odit veniam harum quia, inventore ut esse commodi eligendi quasi, sequi dolorem consequuntur quisquam. Praesentium aperiam, voluptates vitae sunt. Possimus dolorem eius illum quidem.</p>
	<p>Quisquam praesentium ex odit nostrum, beatae non mollitia, magni! Ex tempora inventore aut, magnam expedita reprehenderit itaque quis. Architecto harum optio voluptas, officiis eius similique porro laborum maiores rerum rem!</p>
	<p>Soluta, eaque, aliquam? Cum vero ut ratione, ipsam exercitationem odio architecto atque dolores molestiae, sint, enim! Suscipit provident, animi aut maiores delectus totam quasi eveniet non error, inventore mollitia, sequi.</p>
	<p>Dolor et laudantium vero beatae sed, quaerat dolorum sapiente excepturi totam nam reprehenderit, autem quas unde doloremque expedita placeat labore dolores, quo aliquid! Rerum tempora doloremque itaque commodi sit sed!</p>
	<p>Architecto dolores iusto pariatur, obcaecati odio maxime, vitae consectetur repellat veritatis. Ipsum facilis ipsa dolorum, cumque culpa ex debitis aperiam officiis quaerat, quas iure quidem sequi explicabo a sit aliquid.</p>
	<p>Dolor iste quidem velit officiis nostrum quisquam veniam deserunt magnam rem repellendus sapiente, quasi adipisci dicta ut maiores delectus totam cum quam, architecto vitae ipsa expedita cumque accusantium. Voluptatem, ex?</p>
<?php include 'include/footer.php'; ?>